[tests] #234 - Invoke test (rather than QUnit.test) because travis build failed with message
$ phantomjs qunit-phantomjs-runner/runner.js www/tests/run_qunit.html
ReferenceError: Can't find variable: QUnit
  file:///home/travis/build/olemis/brython/www/tests/run_qunit.html:7

See https://travis-ci.org/olemis/brython/builds/73453739