Fix for javascript error "TypeError: $.get_class is not a function" on python error for treating a number like a string (concatenation)
With python code:
resultString = myNumber + "someString"

when it should be:
resultString = str(myNumber) + "someString"

resulted in javascript error:
"TypeError: $.get_class is not a function"

instead of a more useful exception to show where in the python code the
problem originates from.